[[redirects]]
  from = "/email-signature"
  to = "https://entrepreneurhof.com/induction-dinner/"
  status = 302
  force = true

[[redirects]]
  from = "/email-signature/"
  to = "https://entrepreneurhof.com/induction-dinner/"
  status = 302
  force = true
